name: LeetCode Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: LeetCode Sync
      id: leetcode-sync
      run: node sync.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}

    - name: Debug Response
      if: failure()
      run: |
        echo "Sync failed. Logging response for debugging."
        echo "Response: ${{ steps.leetcode-sync.outputs.response }}"
